### ISSUE TITLE
Training and APi query 

### ISSUE THREAD

**Issue by abhigoku10** [mshenoda/diffugen#1]
@mshenoda  thanks for sharing ur wonderful work i had few queries 
1. mshenoda/realistic_vision_v4 is this custom trained model / repo ? if so can u please given in the details to understand more 
2. for training pipeline should use the link provided in the readme ? what does it generally create 

Thanks in advance

**Comment by mshenoda** [comment]
1. No, the "mshenoda/realistic_vision_v4" is a clone of "SG161222/Realistic_Vision_V4.0_noVAE" 
I did not train it, simply there for a reference/backup in case the original one goes away!

2. training link provided in the readme for training textual inversion embedding, so that you could expand your diffusion model with new object or style concepts. You can read more about this approach in the original paper: https://arxiv.org/abs/2208.01618
